### ISSUE TITLE
Cannot set statusText and status code is always 0

### ISSUE THREAD

**Issue by beradrian** [vladlavrik/netify#20]
It seems that I cannot set the statusText for a Local response. Also I receive a status code of 0, not the one that I just set.

**Comment by vladlavrik** [comment]
I just checked with the latest Chrome (96.0.4664.93) and in my case the status code is working correctly, as you can see in the video.
https://user-images.githubusercontent.com/10566567/144996867-56b91ec3-70ee-4209-98bf-967d666c51f4.mov

Please describe your problem in more detail, the video will be most illustrative.

**Comment by beradrian** [comment]
Have you tried with a status of 400?

**Comment by vladlavrik** [comment]
Just checked it, it works as well.

**Comment by beradrian** [comment]
It seemed that it clashed with other Chrome extensions. I removed those and now everything seems fine. Thanks a lot and sorry!
