### ISSUE TITLE
Netify modify request body not working anymore?

### ISSUE THREAD

**Issue by CodeYimin** [vladlavrik/netify#21]
Modifying response body isn't working, nothing happens to the body. Using 'text' body mode. Rest of the features like setting headers works. Chrome 96.

**Comment by vladlavrik** [comment]
Please specify whether you mean the body of the response or request (in the title of issue you specified "request", in the message text - "response")?

I just checked in chrome 97.0.4692.71 and it works for me, both for a response and request body.
First of all check please with the latest Chrome version.

If the problem still then, please provide more information:
Are there any other extensions? If there is, is there a problem if you turn them off?
What actions and what filter is specified in the rules used?
If it possible, you can record a small video demo of the problem, it helps a lot.

**Comment by CodeYimin** [comment]
My bad, I meant the request. I will record a video soon.

**Comment by CodeYimin** [comment]
Update: it seems like modifying the request body does in fact work, it's just that chrome Dev tools still displays the old body from the start of the request
