### ISSUE TITLE
Any way to modify only one attribute in a JSON POST body?

### ISSUE THREAD

**Issue by mathiasconradt** [vladlavrik/netify#32]
I only found a way to modify the entire POST body (json), but no way to modify a single attribute within the original JSON, keeping any existing payload items as is.
Any way to reference to incoming/original request?

I'm looking for something like this:

```
{
  "key_a": "${attr.key_a}",
  "key_b": "new value"
}
```

![image](https://user-images.githubusercontent.com/295122/205336730-465be939-6ad4-4d76-87d7-72f34fd581ee.png)

**Comment by vladlavrik** [comment]
Now only a complete replacement of the body is possible.
To solve such cases, the introduction of a request/response processing by user's script is being considered in the future, which will allow you to deep customize any part of request/response.

**Comment by khimnguynnn** [comment]
any update with this feature ?

**Comment by vladlavrik** [comment]
The scriptin feature was released in version 0.4.0

**Comment by vladlavrik** [comment]
I close the issue. If you have some difficulties with this, please create a new issue.

**Comment by khimnguynnn** [comment]
thank you bro
