### ISSUE TITLE
install the extension fail on  chrome 113.0.5672.63 

### ISSUE THREAD

**Issue by zwd321081** [vladlavrik/netify#36]
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/2801107/236665234-a217fbdc-08dd-436f-8b81-e0e70836d4a7.png">
<img width="160" alt="image" src="https://user-images.githubusercontent.com/2801107/236665256-0227bed9-d122-46d5-9f7f-fa79e7d6be1e.png">

**Comment by vladlavrik** [comment]
Thanks for the report.
I cannot reproduce this with the same version of the Chrome.
It is very surprising that there is no panel, creating a panel is a very trivial part of the code.

Try uninstalling and reinstalling the extension, also try deactivating other extensions.
If the problem remains, let me know more about your environment: OS type, is the browser a clean  and official version of Chrome?
