### ISSUE TITLE
Local response needs to support returning CJK characters

### ISSUE THREAD

**Issue by xianghongai** [vladlavrik/netify#43]
Currently Local response returns CJK character exception.

![image](https://github.com/vladlavrik/netify/assets/2075006/249daaa8-e558-4c45-9c85-2765b79e5dc4)

```json
{
    "key": "netify 是一个很赞的扩展"
}
```

**Comment by vladlavrik** [comment]
I checked on the current build of chrome 120.0.6099.129 and found no issues with it.
Perhaps in your case it is displayed incorrectly only at the devtools level, and the client receives the correct data. Please check how the response looks like in the js code.
If there is a problem there as well, describe in which version of the browser you are working.

<img width="809" alt="image" src="https://github.com/vladlavrik/netify/assets/10566567/da52cb8d-5bcc-487a-82d3-d79886c2e1d8">

**Comment by xianghongai** [comment]
#40~22.04.1-Ubuntu

Chromium: Version 120.0.6099.71 (Official Build) snap (64-bit)

**Comment by vladlavrik** [comment]
Have you checked what the response looks like in js? Are the characters corrupted there as well?

```
const response = await fetch("<Request url>");
const responseBody = await response.text();
console.log(responseBody === 'netify 是一个很赞的扩展');
```

**Comment by xianghongai** [comment]
The data returned by the browser's native request has the correct encoding:

![image](https://github.com/vladlavrik/netify/assets/2075006/4282a50f-0d80-4089-89e5-3722cdad62c7)

There is a problem with the extension return:

![image](https://github.com/vladlavrik/netify/assets/2075006/389a4ec2-af6d-4154-9f1b-6620ca4fe3dc)

**Comment by xianghongai** [comment]
It displays normally on the page.

It's just a coding problem in DevTools. That's it for now. Thank you for your reply 🤣.
